<h2 class="page-header"><?php echo $this->translate('We are sorry to hear that you decided to leave us')?></h2>
<div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">
        <i class="fa fa-times"></i>
    </button>
    <?php echo $this->translate('Your account has been deactivated successfully');?><br>
    <?php echo $this->translate('You can decide to reactivate it at any point');?>
</div>