<?php if ($submitted && !$error): ?>
    <div class="box">
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="fa fa-times"></i>
                    </button>
                    <?php echo $this->translate('An E-Mail with instructions has been send to the provided E-Mail-Address')?>
                </div>
            </div>
        </div>
    </div>
<?php else: ?>
    <?php
    $form->setAttribute('action', $this->url('user/forgotPassword'));
    $form->prepare();
    $this->formInput()->setTranslatorTextDomain('allstrings');
    $this->formLabel()->setTranslatorTextDomain('allstrings');
    $this->formSelect()->setTranslatorTextDomain('allstrings');
    $this->formTextarea()->setTranslatorTextDomain('allstrings');
    $this->formRadio()->setTranslatorTextDomain('allstrings');
    $this->formfile()->setTranslatorTextDomain('allstrings');
    $this->formElementErrors()->setTranslatorTextDomain('formerrors');
    echo $this->form()->openTag($form);
    ?>
    <h2 class="page-header center"><?php echo $this->translate('Reset Password') ?>:</h2>

    <div class="box">
        <div class="row">
            <div class="col-md-12">
                <?php echo $this->formLabel($form->get('email')); ?>
            </div>
        </div>
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
            <?php echo $this->formInput($form->get('email')) ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>
        </div><!-- /.form-group -->
        <div class="row">
            <div class="col-md-12">
                <?php echo $this->formLabel($form->get('securityQuestionId')); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formSelect($form->get('securityQuestionId')) ?>
            <?php echo $this->formElementErrors($form->get('securityQuestionId')); ?>
        </div><!-- /.form-group -->
        <div class="row">
            <div class="col-md-12">
                <?php echo $this->formLabel($form->get('securityQuestionAnswer')); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formInput($form->get('securityQuestionAnswer')) ?>
            <?php echo $this->formElementErrors($form->get('securityQuestionAnswer')); ?>
        </div><!-- /.form-group -->
        <div class="row">
            <div class="center">
                <div class="form-group">
                    <?php echo $this->formSubmit($form->get('request')); ?>
                </div>
            </div>
        </div>
        <!-- /.form-group -->
    </div><!-- /.box -->
    <?php echo $this->form()->closeTag() ?>
<?php endif; ?>
