<h3><?php echo $this->translate('If an account with the provided E-Mail Address was found, an E-Mail has been send to it.') ?></h3>
<p>
    <?php echo $this->translate('Please follow the instructions in the E-Mail in order to verify your E-Mail-Address.'); ?>
    <br>
    <?php echo $this->translate('Please also check your Junk/Spam folder.'); ?><br>
    <?php echo $this->translate('If you didn\'t receive an E-Mail please try again.'); ?>
</p>