<?php if ($valid !== null && !$valid): ?>
    <h3><?php echo $this->translate('Invalid link supplied') ?></h3>
    <p>
        <?php echo $this->translate('The requested link was invalid.') ?><br>
        <?php echo $this->translate('This may be invalid due to the following reasons') ?>:<br>
    </p>
    <ul>
        <li><?php echo $this->translate('The security question you chose was not the one you selected when registering') ?></li>
        <li><?php echo $this->translate('The answer to the security question was wrong') ?><?php echo $this->translate('Note that the answer is case sensitive (lower and uppercase)') ?></li>
        <li><?php echo $this->translate('No user with the provided email is in our system') ?></li>
    </ul>
    <p>
        <?php echo $this->translate('If you are 100% sure that all the information you provided was valid or if you forgot the question you set or the answer you gave to this question');?><br>
        <?php echo $this->translate('please contact our support-team here');?>:<br>
        <a class="btn btn-primary"><?php echo $this->translate('Contact support');?></a><br>
        <?php echo $this->translate('Our support-team will then try to help you.');?><br>
    </p>
<?php else: ?>
    <?php
    $form->setAttribute('action', $this->url('user/resetPassword', array('hash' => $hash)));
    $form->prepare();
    $this->formInput()->setTranslatorTextDomain('allstrings');
    $this->formLabel()->setTranslatorTextDomain('allstrings');
    $this->formSelect()->setTranslatorTextDomain('allstrings');
    $this->formTextarea()->setTranslatorTextDomain('allstrings');
    $this->formRadio()->setTranslatorTextDomain('allstrings');
    $this->formfile()->setTranslatorTextDomain('allstrings');
    $this->formElementErrors()->setTranslatorTextDomain('formerrors');
    echo $this->form()->openTag($form);
    ?>
    <h2 class="page-header center"><?php echo $this->translate('Enter new password') ?>:</h2>

    <div class="box">
        <div id="pwd-container">
            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->formLabel($form->get('password')); ?>
                </div>
            </div>
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-key"></i></span>
                <?php
                echo $this->formelement($form->get('passwordStrength'));
                echo $this->formelement($form->get('passwordStrengthScore'));
                echo $this->formInput($form->get('password'));
                ?>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?php
                    echo $this->formElementErrors($form->get('password'));
                    echo $this->formElementErrors($form->get('passwordStrengthScore'));
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="pw_verdict"></div>
                    <div class="pw_errors"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 my-help-text">
                    <span class="pwstrength_viewport_progress"></span> <span
                        class="pwstrength_viewport_verdict"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->formLabel($form->get('confirmPassword')); ?>
                </div>
            </div>
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-key"></i></span>
                <?php
                echo $this->formInput($form->get('confirmPassword'));
                ?>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->formElementErrors($form->get('confirmPassword')); ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="center">
                <div class="form-group">
                    <?php echo $this->formSubmit($form->get('save')); ?>
                </div>
            </div>
        </div>
        <!-- /.form-group -->
    </div><!-- /.box -->
    <?php echo $this->form()->closeTag() ?>
    <?php
    $this->inlineScript()->appendFile($this->basePath() . '/libraries/passwordValidation/validate.js', 'text/javascript');
    $this->inlineScript()->appendFile($this->basePath() . '/libraries/passwordValidation/pwstrength.js', 'text/javascript');
    ?>
    <script type="text/javascript">
        $(document).ready(function () {
            "use strict";
            var options = {};
            options.ui = {
                container: "#pwd-container",
                showErrors: true,
                showStatus: true,
                language: '<?php echo $this->layout()->lang?>',
                viewports: {
                    progress: ".pwstrength_viewport_progress",
                    errors: ".pw_errors",
                    verdict: ".pw_verdict"
                }
            };
            options.common = {
                zxcvbn: false,
                userInputs: ['#email'],
                onKeyUp: function (evt, data) {
                    if (Math.round(data.score) >= 39) {
                        $('#passwordStrength').val("strong");
                    } else {
                        $('#passwordStrength').val('week');
                    }
                    $('#passwordStrengthScore').val(Math.round(data.score));
                }
            };
            $('#password').pwstrength(options);
        });
    </script>
<?php endif; ?>